# Site Settings
title: Exploring RVA
email: therealindependentwolf@gmail.com
description: >
baseurl: "/"
url: "http://exploringrva.com"
github_username:  theindependentwolf
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM